# Generated by Django 5.1 on 2024-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'register_user',
            },
        ),
    ]
