# Generated by Django 5.1 on 2024-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('flower_id', models.AutoField(primary_key=True, serialize=False)),
                ('flower_name', models.CharField(max_length=200)),
                ('flower_price', models.IntegerField()),
                ('flower_description', models.CharField(max_length=255)),
                ('flower_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'flower_table',
            },
        ),
    ]
