# Generated by Django 5.1 on 2024-08-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.flower')),
            ],
        ),
    ]
