# Generated by Django 5.1 on 2024-08-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0002_add_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_cart',
            new_name='AddCart',
        ),
    ]
