# Generated by Django 5.1 on 2024-08-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0003_rename_add_cart_addcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='flower_description',
            field=models.TextField(),
        ),
    ]
