# Generated by Django 5.1 on 2024-08-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0004_alter_flower_flower_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('buy_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('razorpay_id', models.CharField(max_length=255)),
                ('paid', models.BooleanField(default=False)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.flower')),
            ],
        ),
    ]
