# Generated by Django 5.1 on 2024-09-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0004_alter_flower_flower_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesFlower',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'imgs_table',
            },
        ),
        migrations.CreateModel(
            name='PanUser',
            fields=[
                ('pan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=50)),
                ('pan_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'pan_user_table',
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('name', models.CharField(default=1, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(default=1, max_length=255)),
                ('password', models.CharField(max_length=12)),
                ('image', models.ImageField(default='person.jpg', upload_to='')),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.AlterModelTable(
            name='addcart',
            table='cart_table',
        ),
        migrations.AlterModelTable(
            name='flower',
            table='flowers_table',
        ),
        migrations.AddField(
            model_name='flower',
            name='flower_img',
            field=models.ForeignKey(default='person.jpg', on_delete=django.db.models.deletion.CASCADE, to='flowerapp.imagesflower'),
        ),
    ]
