# Generated by Django 5.1 on 2024-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0006_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='image',
            field=models.ImageField(default='person.jpg', upload_to=''),
        ),
    ]
