# Generated by Django 5.1 on 2024-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0008_userregister_address_userregister_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanUser',
            fields=[
                ('pan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=50)),
                ('pan_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'panuser_table',
            },
        ),
    ]
