# Generated by Django 5.1 on 2024-12-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0005_imagesflower_panuser_userregister_and_more'),
        ('flowerapp', '0009_panuser'),
    ]

    operations = [
    ]
