# Generated by Django 5.1 on 2024-12-06 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0010_merge_20241206_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='flower_img',
        ),
        migrations.AddField(
            model_name='addcart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowerapp.userregister'),
        ),
        migrations.AlterModelTable(
            name='addcart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='flower',
            table='flower_table',
        ),
        migrations.AlterModelTable(
            name='userregister',
            table=None,
        ),
        migrations.DeleteModel(
            name='ImagesFlower',
        ),
    ]
