# Generated by Django 5.1 on 2024-12-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0011_remove_flower_flower_img_addcart_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='panuser',
            table='panuser_table',
        ),
    ]
